## Numpy

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [4]:
a=np.array ([[1,2],[3,5]])
print(a)

[[1 2]
 [3 5]]


In [5]:
b=np.array([[2,5],[7,9]])

In [6]:
print(a+b)

[[ 3  7]
 [10 14]]


In [7]:
a=[i for i in range(10)]
print(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [8]:
import time 

b=[i for i in range(int(1e5))]
start_time = time.time()
b=b*2
end_time = time.time()

print("Time taken:", end_time - start_time)


Time taken: 0.005455493927001953


In [9]:
np_array = np.array([i for i in range(int(1e5))])
start_time = time.time()
np_array=np_array*2
end_time = time.time()
print("Time taken:", end_time - start_time)

Time taken: 0.0002894401550292969


In [10]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [11]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [12]:
print(np.full((3,2),1))

[[1 1]
 [1 1]
 [1 1]]


In [13]:
print(np.random.random((2,3)))

[[0.84040764 0.96923901 0.64542322]
 [0.86217063 0.6219701  0.12291726]]


In [14]:
py_list=[1,2,3]
print(py_list*2)

[1, 2, 3, 1, 2, 3]


In [15]:
py_np=np.array([1,2,3])
print(py_np*2)

[2 4 6]


In [16]:
zeros=np.zeros((2,3,2,2))
print(zeros)

[[[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]]


In [17]:
full=np.full((2,3),7)
print(full)

[[7 7 7]
 [7 7 7]]


In [18]:
random=np.random.random((3,2))
print(random)

[[0.1942337  0.39405785]
 [0.8139626  0.79836231]
 [0.32296867 0.1672519 ]]


In [19]:
sequence=np.arange(0,7,3/4)
print(sequence)
print(type(sequence))

[0.   0.75 1.5  2.25 3.   3.75 4.5  5.25 6.   6.75]
<class 'numpy.ndarray'>


## Vector, Matrix and Tensor

In [20]:
vector=np.array([14,2,4,5,6])
print(vector)

[14  2  4  5  6]


In [24]:
matrix=np.array([[1,2,3],[4,5,6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [27]:
tensor=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(tensor*2)

[[[ 2  4]
  [ 6  8]]

 [[10 12]
  [14 16]]]


# Array Properties

In [ ]:
arr = np.array([1,2,3],[9,6,3])

print(arr.)